# Generated by Django 6.0.2 on 2026-02-18 16:23

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_sector',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(max_length=16, validators=[users.validators.validate_nid]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[users.validators.validate_phone_number]),
        ),
    ]
