# Generated by Django 6.0.2 on 2026-02-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_user_is_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_otp_sent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.AddField(
            model_name="user",
            name="is_nid_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="yob",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
