# Generated by Django 6.0.2 on 2026-02-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_last_otp_sent_remove_user_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
