# Generated by Django 6.0.2 on 2026-03-05 11:18

import users.validators
import utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=utils.encryption.EncryptedCharField(max_length=16, validators=[users.validators.validate_nid]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tin',
            field=utils.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
