# Generated by Django 6.0.2 on 2026-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.CharField(max_length=255)),
                ("shipment_date", models.DateField()),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                (
                    "shipment_type",
                    models.CharField(
                        choices=[
                            ("international", "International"),
                            ("domestic", "Domestic"),
                        ],
                        max_length=255,
                    ),
                ),
                ("shipment_weight", models.FloatField()),
                ("shipment_volume", models.FloatField()),
                ("shipment_value", models.FloatField()),
                ("country_of_origin", models.CharField(max_length=255)),
                ("location_of_origin", models.CharField(max_length=255)),
                ("country_of_destination", models.CharField(max_length=255)),
                ("location_of_destination", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
