# Generated by Django 6.0.2 on 2026-02-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="shipment_id",
        ),
    ]
