# Generated by Django 6.0.2 on 2026-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_remove_shipment_shipment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="shipment_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
