# Generated by Django 6.0.2 on 2026-02-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_alter_shipment_shipment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
