# Generated by Django 6.0.2 on 2026-02-22 08:04

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0005_alter_shipment_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="phone_number",
            field=models.CharField(
                max_length=255, validators=[users.validators.validate_phone_number]
            ),
        ),
    ]
