# Generated by Django 6.0.2 on 2026-02-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0006_alter_shipment_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="passport_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="tin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
