# Generated by Django 6.0.2 on 2026-02-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0007_shipment_passport_number_shipment_tin"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalShipment",
            fields=[
                (
                    "shipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "International Shipment",
            },
            bases=("shipments.shipment",),
        ),
    ]
